### ISSUE TITLE
Fix ability to place more than one tower on one block in multiplayer

### ISSUE THREAD

**Issue by tbvns** [WyndevCodes/Minestom-Tower-Defense#13]
![Image](https://github.com/user-attachments/assets/df9b53e0-0686-462d-8089-320a865f0b60)

**Comment by WyndevCodes** [comment]
Could you verify that this is still an issue? Based on the screenshot (where I cannot tell that there are multiple towers in the same block) and the code, it doesn't seem like it should ever happen.

**Comment by tbvns** [comment]
![image](https://github.com/user-attachments/assets/6f45f2fe-ae45-4b56-b10d-ae898afbd455)
right here, and I think I already fixed in in multiplayer update, I need to check that.
